#ifndef _ASM330LHBG1
#define _ASM330LHBG1

#include "stdbool.h"
#include "stm32h7xx_hal.h"

typedef enum {
    FUNC_CFG_ACCESS        = 0x01,
	PIN_CTRL 			   = 0x02,
    SENSOR_SYNC_TIME_FRAME = 0x04,
    SENSOR_SYNC_RES_RATIO  = 0x05,
    FIFO_CTRL1             = 0x06,
    FIFO_CTRL2             = 0x07,
    FIFO_CTRL3             = 0x08,
    FIFO_CTRL4             = 0x09,
    FIFO_CTRL5             = 0x0A,
    ORIENT_CFG_G           = 0x0B,
    INT1_CTRL              = 0x0D,
    INT2_CTRL              = 0x0E,
    WHO_AM_I_IMU              = 0x0F,
    CTRL1_XL               = 0x10,
    CTRL2_G                = 0x11,
    CTRL3_C                = 0x12,
    CTRL4_C                = 0x13,
    CTRL5_C                = 0x14,
    CTRL6_C                = 0x15,
    CTRL7_G                = 0x16,
    CTRL8_XL               = 0x17,
    CTRL9_XL               = 0x18,
    CTRL10_C               = 0x19,
    ALL_INT_SRC            = 0x1A,
    WAKE_UP_SRC            = 0x1B,
    TAP_SRC                = 0x1C,
    D6D_SRC                = 0x1D,
    STATUS_REG_IMU            = 0x1E,
    OUT_TEMP_L             = 0x20,
    OUT_TEMP_H             = 0x21,
    OUTX_L_G               = 0x22,
    OUTX_H_G               = 0x23,
    OUTY_L_G               = 0x24,
    OUTY_H_G               = 0x25,
    OUTZ_L_G               = 0x26,
    OUTZ_H_G               = 0x27,
    OUTX_L_A               = 0x28,
    OUTX_H_A               = 0x29,
    OUTY_L_A               = 0x2A,
    OUTY_H_A               = 0x2B,
    OUTZ_L_A               = 0x2C,
    OUTZ_H_A               = 0x2D,
    EMB_FUNC_STATUS_MAINPAGE = 0x35,
    FSM_STATUS_A_MAINPAGE  = 0x36,
    FSM_STATUS_B_MAINPAGE  = 0x37,
    STATUS_MASTER_MAINPAGE = 0x39,
    FIFO_STATUS1           = 0x3A,
    FIFO_STATUS2           = 0x3B,
    TIMESTAMP0_REG         = 0x40,
    TIMESTAMP1_REG         = 0x41,
    TIMESTAMP2_REG         = 0x42,
    STEP_TIMESTAMP_L       = 0x49,
    STEP_TIMESTAMP_H       = 0x4A,
    STEP_COUNTER_L         = 0x4B,
    STEP_COUNTER_H         = 0x4C,
    EMB_FUNC_FIFO_STATUS   = 0x4D,
    FSM_ENABLE_A           = 0x4E,
    FSM_ENABLE_B           = 0x4F,
    EMB_FUNC_INIT_A        = 0x50,
    EMB_FUNC_INIT_B        = 0x51,
    FSM_LONG_COUNTER_L     = 0x52,
    FSM_LONG_COUNTER_H     = 0x53,
    EMB_FUNC_SRC           = 0x56,
    FSM_OUTS1              = 0x58,
    FSM_OUTS2              = 0x59,
    FSM_OUTS3              = 0x5A,
    FSM_OUTS4              = 0x5B,
    FSM_OUTS5              = 0x5C,
    FSM_OUTS6              = 0x5D,
    FSM_OUTS7              = 0x5E,
    FSM_OUTS8              = 0x5F,
    FSM_OUTS9              = 0x60,
    FSM_OUTS10             = 0x61,
    FSM_OUTS11             = 0x62,
    FSM_OUTS12             = 0x63,
    FSM_OUTS13             = 0x64,
    FSM_OUTS14             = 0x65,
    FSM_OUTS15             = 0x66,
    FSM_OUTS16             = 0x67,
    EMB_FUNC_ODR_CFG_B     = 0x7F,
    I3C_BUS_AVB            = 0x62,
    INTERNAL_FREQ_FINE     = 0x63
} imu_reg_t;

uint8_t generateIMUAddress(imu_reg_t imuRegNum, bool readFlag);
uint8_t ensureIMUNotReserved(imu_reg_t regToCheck);
uint8_t writeIMURegister(SPI_HandleTypeDef* imuSPI, imu_reg_t imuRegNum, uint8_t valueToWrite);
uint8_t readIMUSingleRegister(SPI_HandleTypeDef* imuSPI, imu_reg_t imuRegNum);
uint16_t readIMUDoubleRegister(SPI_HandleTypeDef* imuSPI, imu_reg_t upperRegAddress, imu_reg_t lowerRegAddress);

#endif